### ISSUE TITLE
Change key rotation test to typical rotation flow

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#100]
Change key rotation test to typical rotation flow which is:
1. Message pump starts up which is using primary connection string
2. Rotation process rolls the secondary key
3. Rotation process sets the secondary key in Key Vault
4. Rotation process rolls the primary key which revokes access
5. Message pump detects unauthorized exceptions
6. Message pump gracefully shuts down
7. Message pump starts up with new connection string from vault

**Comment by stijnmoreels** [comment]
So, to make it test-practical. This should be the flow:

**Test infrastructure**
1. Rotation process rolls primary connection string
2. Rotation process sets primary key in Key Vault

**Message pump**
3. Mesage pump starts which is using the primary connection string

**Test infrastructure**
4. Rotation process rolls the primary & secondary key (which revokes access)
5. Rotation process sets secondary key in Key Vault

**Message pump**
6. Message pump detects unauthorized exceptions
7. Message pump gracefully shuts down
8. Message pump starts up with new secondary connection string from Key vault

**Test infrastructure**
9. Send message to message pump to see if it still processes correclty

**Comment by tomkerkhove** [comment]
> **Test infrastructure**
> 4. Rotation process rolls the primary & secondary key (which revokes access)
> 5. Rotation process sets secondary key in Key Vault

This is actually:
4.  Rotation process rolls the secondary key
5. Rotation process sets secondary key in Key Vault
6.  Rotation process rolls the primary key (which revokes access)

For the rest it looks ok!

**Comment by stijnmoreels** [comment]
I'll need some help with creating all the required resources now being reused from the EventGrid project.
We need more than just a service bus and I think there's a ARM deployment but I remember struggling before and using the EventGrid instead.

**Comment by tomkerkhove** [comment]
You should be able to do that via the portal and need the following at least:
- Service Bus namespace with topic (to send events to) and queue (to process work in test)
- Event Grid topic with a subscription (sends all events to topic)
- Key Vault

If you're stuck, let me know.

**Comment by stijnmoreels** [comment]
Hmm, I tried [this](https://eventgrid.arcus-azure.net/features/running-integration-tests#azure-infrastructure) walkthrough to set up the infrastructure, but that doesn't create the API connection and Logic App required for this. How can this be created, then?

**Comment by tomkerkhove** [comment]
Which Logic App do you need?

**Comment by stijnmoreels** [comment]
IDK, I just saw that the infrastructure in the EventGrid group a separate API connection, Logic App, Service Bus Topic, and Event Grid Topic. So, I figured we would need that in the messaging too if we want to test our messaging integration tests (since we now fully use the EventGrid resources for this).

**Comment by tomkerkhove** [comment]
Forget what you see there, let's just focus on [what we want](https://github.com/arcus-azure/arcus.messaging/issues/100#issuecomment-664129266) :) 

Back in the day a Logic App was required but now you can send it straight to Service Bus Topic.
