### ISSUE TITLE
Provide logic to rotate Service Bus secrets

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#102]
**Is your feature request related to a problem? Please describe.**
Provide logic to rotate Service Bus secrets as part of our applications.

**Describe the solution you'd like**
It should be able to rotate one key, set it in Key Vault and rotate the other afterwards. On the next run, it should do the same but in other order or give consumers the option to specify the keys they want to rotate.

For example:
- First run it should rotate secondary, set secondary, rotate primary
- Second run it should rotate primary, set primary, rotate secondary

This should be able to run as Arcus Background Job or in something else such as in an Azure Function with a timer.

**Comment by stijnmoreels** [comment]
Question: I guess these two runs will then every time run periodically. I was wondering why we have the same action at the end and beginning of each run. (ex. rotate primary is the same last action as the beginning of the second run).
I was wondering why we rotate the same key twice.

**Comment by tomkerkhove** [comment]
You mean why primary is rotated in this case?

> First run it should rotate secondary, set secondary, rotate primary

That's to ensure that people who are not fetching the latest secret are revoked access.
