### ISSUE TITLE
Provide capability to influence handling of Service Bus message in a handler

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#118]
**Is your feature request related to a problem? Please describe.**
Provide capability to influence handling of Service Bus message in a handler so that we can decide to complete, defer, abandon, deadletter, etc the message from within the handler itself.

**Describe the solution you'd like**
Today we have the following interfaces:
- [`IAzureServiceBusMessageHandler`](https://github.com/arcus-azure/arcus.messaging/blob/master/src/Arcus.Messaging.Pumps.ServiceBus/IAzureServiceBusMessageHandler.cs)
- [`IAzureServiceBusFallbackMessageHandler`](https://github.com/arcus-azure/arcus.messaging/blob/master/src/Arcus.Messaging.Pumps.ServiceBus/MessageHandling/IAzureServiceBusFallbackMessageHandler.cs)

It might be interesting to have the following:
- `AzureServiceBusMessageHandler`
- `AzureServiceBusFallbackMessageHandler`

Which provides methods such as `Deadletter(message, newMessageProperties)`, `Abandon(message, newMessageProperties)` so that we can make those decisions ourselves

**Describe alternatives you've considered**
Nothing concrete in mind.

**Comment by tomkerkhove** [comment]
What do you think @stijnmoreels? This would mean that those base classes have `MessageReceiver` as a private field which is being used.

**Comment by stijnmoreels** [comment]
Hmm, yeah, that seems an elegant solution. But it would be nice to use them besides each other, right? I think that's what you mean. That you you can choose to inherit these classes if you want finer control over the message? I'll have to think of a way to send the `MessageReceiver` of the message pump 'internally' to these classes, but I think it can be done!
Nice one!

**Comment by tomkerkhove** [comment]
Yes, that's is what I meant. By default I can use the interface but if I want control over the message operations I have to use the default Azure Service Bus handler.

I was thinking of injecting it in the constructor (and thus my handler has to pass it) but not sure if that will work with the way it works now.

**Comment by stijnmoreels** [comment]
I think I maybe can inject it, but it would have to be something else then the `MessageReceiver` itself bc we allow multiple message pumps.

**Comment by stijnmoreels** [comment]
Hmm, I'll do not with that approach, bc we also allow a single message handler to handle message from different message pumps, so we have to initialize the message receiver at a later time.
