### ISSUE TITLE
Provide capability to reject TCP connections when dependencies are unhealthy

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#131]
**Is your feature request related to a problem? Please describe.**
Provide the capability to reject TCP connections when dependencies are unhealthy.

Otherwise, runtimes such as Kubernetes will consider the application healthy anyway because it's just checking if it can set up a connection. If it does, it's considered to be healthy, regardless of the payload it receives.

**Describe the solution you'd like**
We should provide an opt-in to reject connections when it's unhealthy.

**Comment by stijnmoreels** [comment]
I forget what this is about. Is it about tracking the health of the message pump itself so that we can update the health status exposed by the TCP connection?

**Comment by tomkerkhove** [comment]
> **Is your feature request related to a problem? Please describe.**
> Provide the capability to reject TCP connections when dependencies are unhealthy.
> We should provide an opt-in to reject connections when it's unhealthy.

This should be clear, no?

**Comment by stijnmoreels** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > Provide the capability to reject TCP connections when dependencies are unhealthy.
> > We should provide an opt-in to reject connections when it's unhealthy.
> 
> This should be clear, no?

Hmmm, well, no, not sure which part should reject what. Should we reject something (something that's not yet used), or should we send out more message pump-related health status codes?

**Comment by tomkerkhove** [comment]
If the health is no longer considered healthy we should no longer accept TCP connections and thus shut down the endpoint (opt-in)
