### ISSUE TITLE
Provide correlation information for unhandled exceptions in message handlers

### ISSUE THREAD

**Issue by FilipVanRaemdonck** [arcus-azure/arcus.messaging#132]
**Is your feature request related to a problem? Please describe.**
When a custom AzureServiceBusMessageHandler is unable to process a message it throws an error. This error is logged in application insights without correlation information (operationId, transactionId). This makes it hard to correlate the error with other application insights logs.

**Describe the solution you'd like**
The Service Bus Message we couldn't process very likely contains correlation information. It would be good to have these (optionally) in the logs coming from the Arcus Framework.

**Describe alternatives you've considered**
An alternative might be to allow the user to provide a custom error handling function.

**Comment by tomkerkhove** [comment]
Updated the description a bit. Can you please post an example @FilipVanRaemdonck?

@stijnmoreels For some reason, when using correlation enrichment, it does not include the correlation information when tracking exceptions. Now in this case it was related to the interaction with the queue which I think is fair but we'll need to make sure everything is handled correctly.

**Comment by FilipVanRaemdonck** [comment]
![image](https://user-images.githubusercontent.com/14161827/97332117-5ff68400-187a-11eb-98f0-d6bfc009699e.png)

**Comment by tomkerkhove** [comment]
Context for @stijnmoreels, we are looking up secrets as part of the handlers through `ISecretProvider` where it couldn't find one.

**Comment by stijnmoreels** [comment]
OK, and the incoming message contains this correlation information? Could there be a sample of a message and it's properties? Bc the correlation will only be available if the operation and transaction ID is available as properties in the message.

**Comment by FilipVanRaemdonck** [comment]
The correlationId and transactionId are part of the Message properties. The Correlation id is the message's Correlation id, the transactionId is part of the user properties. But you might have to take into account the transactionId name is configurable (https://github.com/arcus-azure/arcus.messaging/pull/126)

**Comment by tomkerkhove** [comment]
@FilipVanRaemdonck can you export a message through Service Bus Explorer (incl. headers) and upload an obfuscated version here please?

**Comment by FilipVanRaemdonck** [comment]
![image](https://user-images.githubusercontent.com/14161827/97415761-e4daaf80-1905-11eb-99d0-7a0f1717544c.png)
Here you are :D

**Comment by FilipVanRaemdonck** [comment]
Would it make sense to put all message custom properties in the logs?

**Comment by tomkerkhove** [comment]
Nope, should be good - Thanks!

**Comment by stijnmoreels** [comment]
Oh, yeah, I see it. The correlation is set but the message handler exception is logged outside the scope of the serilog enrichment.
We can change that.

**Comment by tomkerkhove** [comment]
Thanks man!

**Comment by tomkerkhove** [comment]
This is available in https://github.com/arcus-azure/arcus.messaging/releases/tag/v0.5.1
