### ISSUE TITLE
Provide support for managed identity authentication for Azure Service Bus message pump

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#137]
**Is your feature request related to a problem? Please describe.**
Provide support for managed identity authentication for Azure Service Bus message pump. 

This would allow us to use 0 secrets. 

**Describe the solution you'd like**
A new extension that does not require a secret name, but explicitly state it uses Managed Identity.

**Comment by stijnmoreels** [comment]
How does this fit in with retrieving the service bus connection string?

**Comment by tomkerkhove** [comment]
I doesn't because there won't be a connection string anymore, Managed Identity handles the authentication for you through Azure AD authentication. You can learn more about it on [here](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview).

**Comment by tomkerkhove** [comment]
This is supported in the new Identity SDK and is similar to how Key Vault auth support managed identity.

**Comment by stijnmoreels** [comment]
Yes, I see. Is this something you want to support backwards compatible? As in, we support both our current and the new Identity SDK at the same time?

**Comment by tomkerkhove** [comment]
For now I think it's ok to just add the managed identity authentication, it does not perse have to be with the new SDK.

If you think it's best to mix in the new SDK then that's ok but would become 1.0 then

**Comment by stijnmoreels** [comment]
Hmm, I'm still not sure if I get this correctly. The managed identity works indeed without connection string, but with access tijdens which is passed along a service that connects with the resource. But that service lives in the new SDK, so I'm not sure how we can benefit from this without using the SDK. Is there some way to integrate the managed identity that we can generate a connection string or some sort bc our `MessageReceicer` requires this.

**Comment by tomkerkhove** [comment]
The service is not inside the SDK as this runs in Azure itself; I thought it was possible with the old SDK but if it isn't, then we should migrate to Azure.Identity package as well.

If you prefer to not change 0.6 into 1.0 we can do that in the next release; this is not a burning issue

**Comment by tomkerkhove** [comment]
This should be possible AFAIK (https://github.com/Azure-Samples/app-service-msi-servicebus-dotnet/blob/master/WebAppServiceBus/WebAppServiceBus/Controllers/HomeController.cs#L62)

**Comment by stijnmoreels** [comment]
Ok, I think I have something I want to test, but I'm not sure how we should approach this authentication mechanism in our Arcus Azure resources. Should we create one user-assigned identity across all?
