### ISSUE TITLE
Provide basic message pump for Azure Service Bus

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#14]
We should make it very simple to create a worker that dequeues messages, does some work and deletes it on the queue (peek-lock, not receive-delete).

The focus of the worker should be to process the message and not the infrastructure around it.

## Scope
Current scope of this feature is to simply write a message handler and leave the message pump itself to Arcus.

Every message handler writer must be able to:
- Have control over the logging in terms of verbosity level, sinks, etc.
- Have control over the queue & namespace that is being processed
- Have control over exceptions to be able to react on them and influence message property (ie. track processing state), but only when opt-ed in

The message pump itself must:
- Provide telemetry on every step
- Automatically wire-up correlation for all telemetry so that the message handler writer should not have to worry about it
- Handle exceptions by abandoning them

As of now, we will only support one message contract but later on we could provide the capability to handle multiple data contracts but that is out-of-scope for now.

## Discussion Topics

- How do you want to define what queue to process? Configuration, hard-coded, etc.
- How do you prefer to register the pump? Is the convenient method describe below ok or do you want it to be done automagically?
- How often do you run multiple pumps in one app? This feels out of scope to me but open for ideas.
- What do you think about the approach mentioned above?
- How much control do you want?
- What information from the message do you typically need, other than the body?
- What serialization formats do you use? How do you want to specify this? Would a ~`QueueWorkerOptions` be good for you?

## Rough Idea
An idea is that you could simply derive from a worker that we provide and specify the type of the message contract that you expect.

This is what it could look like for example:
```csharp
public class OrdersQueueProcessor : AzureServiceBusQueueWorker<Order>
{
    public OrdersQueueProcessor(IConfiguration configuration, ILogger<OrdersQueueProcessor> logger)
        : base(configuration, logger)
    {
    }

    protected override async Task ProcessMessage(Order order, MessageContext messageContext, CancellationToken cancellationToken)
    {
        Logger.LogInformation("Processing order {OrderId} for {OrderAmount} units of {OrderArticle} bought by {CustomerFirstName} {CustomerLastName}", order.Id, order.Amount, order.ArticleNumber, order.Customer.FirstName, order.Customer.LastName);

        await Task.Delay(TimeSpan.FromSeconds(2), cancellationToken);

        Logger.LogInformation("Order {OrderId} processed", order.Id);
    }
}
```

Where `MessageContext` would give your general message context such as user properties, system properties, correlation id, etc.

Behind the scenes it will spin up a message pump for you which does all the deserialization, exception handling (although we should provide capability to opt-in to extend it), 

```csharp
public abstract class QueueWorker<TMessage> : BackgroundService
    {
        protected ILogger<QueueWorker<TMessage>> Logger { get; }
        protected IConfiguration Configuration { get; }

        public QueueWorker(IConfiguration configuration, ILogger<QueueWorker<TMessage>> logger)
        {
            Configuration = configuration;
            Logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            var connectionString = Configuration.GetValue<string>("KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING");

            var serviceBusConnectionStringBuilder = new ServiceBusConnectionStringBuilder(connectionString);

            var queueClient = new QueueClient(serviceBusConnectionStringBuilder.GetNamespaceConnectionString(), serviceBusConnectionStringBuilder.EntityPath, ReceiveMode.PeekLock);

            Logger.LogInformation("Starting message pump");
            queueClient.RegisterMessageHandler(HandleMessage, HandleReceivedException);
            Logger.LogInformation("Message pump started");

            while (!stoppingToken.IsCancellationRequested)
            {
                await Task.Delay(TimeSpan.FromSeconds(1));
            }

            Logger.LogInformation("Closing message pump");
            await queueClient.CloseAsync();
            Logger.LogInformation("Message pump closed : {Time}", DateTimeOffset.UtcNow);
        }

        private Task HandleReceivedException(ExceptionReceivedEventArgs exceptionEvent)
        {
            Logger.LogError(exceptionEvent.Exception, "Unable to process message");
            return Task.CompletedTask;
        }

        protected abstract Task ProcessMessage(TMessage order, string messageId, Message.SystemPropertiesCollection systemProperties, IDictionary<string, object> userProperties, CancellationToken cancellationToken);

        private async Task HandleMessage(Message message, CancellationToken cancellationToken)
        {
            var rawMessageBody = Encoding.UTF8.GetString(message.Body);
            Logger.LogInformation("Received message {MessageId} with body {MessageBody}", message.MessageId, rawMessageBody);

            var order = JsonConvert.DeserializeObject<TMessage>(rawMessageBody);
            if (order != null)
            {
                await ProcessMessage(order, message.MessageId, message.SystemProperties, message.UserProperties, cancellationToken);
            }
            else
            {
                Logger.LogError("Unable to deserialize to message contract {ContractName} for message {MessageBody}", typeof(TMessage), rawMessageBody);
            }

            Logger.LogInformation("Message {MessageId} processed", message.MessageId);
        }
    }
```

The host itself is simply configured as following:
```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.AddEnvironmentVariables();
                })
                .ConfigureLogging((hostBuilderContext, loggingBuilder) =>
                {
                    loggingBuilder.AddConsole(consoleLoggerOptions => consoleLoggerOptions.TimestampFormat = "[HH:mm:ss]");
                })
                .ConfigureServices(services =>
                {
                    services.AddHostedService<OrdersQueueProcessor>();
                });
```

We should, however, provide a conventient way to register the processor rather than via the `ConfigureServices` approach, but something like `WithQueueWorker<OrdersQueueProcessor>` or something similar instead.

All of the above suggestions are based on [a small sample](https://github.com/kedacore/sample-dotnet-worker-servicebus-queue) that I've created but it should be polished a bit to make it more robust and decent for production workloads, but it proves a bit what I want to achieve and am open to suggestions.

**Comment by fgheysels** [comment]
I've quickly gone over this and overall, it looks good to me.  I agree that registering the worker should be more straightforward.

I just do not like the loop which is simply there to make sure that the worker is kept alive.  I'd rather try something like this:

```csharp
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    var queueClient = new QueueClient(....);

    await UntilCancelled(stoppingToken);

    await queueClient.CloseAsync();
}


private static Task UntilCancelled(CancellationToken cts)
{
    var tcs = new TaskCompletionSource<bool>();
    cts.Register(s => ((TaskCompletionSource<bool>)s).SetResult(true), tcs);

    return tcs.Task;
 }
```

**Comment by tomkerkhove** [comment]
That's ok for me - I'll work on a proposal PR in the next couple of weeks. Feel free to review that one!

Will first work on a rough version without tests to pass the initial PR and then polish it a bit and add tests.

**Comment by tomkerkhove** [comment]
Code ✔️ 
Docs: :x:

Will do that tomorrow.

**Comment by stijnmoreels** [comment]
> Code ✔️
> Docs: ❌
> 
> Will do that tomorrow.

Meanwhile...
![image](https://user-images.githubusercontent.com/9039753/73724960-bcce6f00-472c-11ea-91ba-496a90a827dc.png)

**Comment by tomkerkhove** [comment]
😂
