### ISSUE TITLE
Provide capability to use Azure Service Bus plugins

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#149]
**Is your feature request related to a problem? Please describe.**
Provide capability to use Azure Service Bus plugins with the SDK, for example: https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin

**Comment by tomkerkhove** [comment]
This would be a good one to add @stijnmoreels

**Comment by stijnmoreels** [comment]
Plugins are not yet supported on the new SDK, so not sure if we should already do this on the 'old' `Message`?

**Comment by tomkerkhove** [comment]
It depends how soon we kill the old one; if that will take a couple of versions then I would say we do it

**Comment by stijnmoreels** [comment]
I'm not sure though what this issue is about. We already allow plugins to be registered in the message pump.

**Comment by tomkerkhove** [comment]
Then the issue is docs because I couldn't recall if we supported it, went to the docs and didn't find anything on it 🤔

**Comment by stijnmoreels** [comment]
> Then the issue is docs because I couldn't recall if we supported it, went to the docs and didn't find anything on it 🤔

That could be very much so, other things like deadletter/abandon capacity via overriden message pump methods isn't also mentioned in the docs bc I think it was supposed to be something that the user can see for themselves when they have to implement their own message pump.

**Comment by stijnmoreels** [comment]
@tomkerkhove , this is what you meant, right, with supporting plugins? 
https://github.com/arcus-azure/arcus.messaging/blob/afd4d8f2c10cd5ed61a1df15c067dfbaee15b742/src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs#L473
We can indeed add this explicitly to the docs and close this issue then?
