### ISSUE TITLE
Add ContentType to AzureServiceBusSystemProperties (Arcus.Messaging.Abstractions.ServiceBus)

### ISSUE THREAD

**Issue by SebastienWojtyla** [arcus-azure/arcus.messaging#183]
**Is your feature request related to a problem? Please describe.**
Currently we are trying to make a distinction between messages based on the contentType but unfortunately, arcus doesn't support this property.

**Describe the solution you'd like**
In AzureServiceBusSystemProperties add the following property : ContentType. This is already a property from ServiceBusReceivedMessage but is currently not getting used
![image](https://user-images.githubusercontent.com/79199130/119816699-4d662b00-beed-11eb-8303-356fc6e9488b.png)

**Comment by tomkerkhove** [comment]
Happy to add it, are you willing to contribute this?

**Comment by SebastienWojtyla** [comment]
Sure, I can add this :)

**Comment by tomkerkhove** [comment]
Thank you!

**Comment by stijnmoreels** [comment]
> Sure, I can add this :)

Thanks a lot!

**Comment by tomkerkhove** [comment]
Thank you for your contribution in #184 !
