### ISSUE TITLE
Provide unit tests for AzureServiceBusSystemProperties 

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#185]
Provide unit tests for AzureServiceBusSystemProperties  to verify that we are assigning things correctly.

**Comment by stijnmoreels** [comment]
Would be great if we used Lenses for this, but maybe to far for starter devs.

**Comment by tomkerkhove** [comment]
I have never heard about that before, can you elaborate on it please?

**Comment by stijnmoreels** [comment]
'Lenses' is a programming concept mostly known in functional programming languages. It's basically a way of describing getter/setters on immutable types as functions, as a first-class citizen. As you may know, they tend to describe everything in FP as a function, and this is a logical result of that.
