### ISSUE TITLE
Don't create Azure Service Bus topic subscriptions on start-up

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.messaging#216]
**Is your feature request related to a problem? Please describe.**
In the new version, the `TopicSubscription` enum hasn't got a `None` member anymore but has become a nullable enumeration.

We should verify if this indeed is the most user-friendly option.

**Describe the solution you'd like**
We should update the migration guide, if necessary to reflect this.

**Additional context**
First noticed by @SebastienWojtyla

**Comment by tomkerkhove** [comment]
> We should update the migration guide, if necessary to reflect this.

Yes please!

**Comment by stijnmoreels** [comment]
> > We should update the migration guide, if necessary to reflect this.
> 
> Yes please!

First, we need to determine if we should reintroduce the `None` enum member (or something similar).

**Comment by tomkerkhove** [comment]
Do you have some code samples? That would make it easier.

**Comment by SebastienWojtyla** [comment]
In the version that we are currently using on our project (0.6) in the the TopicSubscription there was a None option which has been removed in 1.0 and I didn't know that I had to replace the None option by null.
![image](https://user-images.githubusercontent.com/79199130/131453302-e3befb1d-2845-4473-ac83-c9becd27c0a0.png)

**Comment by tomkerkhove** [comment]
Ah this is our enum - I thought it was an official one.

Frankly, I prefer to re-introduce None and use that as a default @stijnmoreels? It's more explicit when reading the code imo.

**Comment by stijnmoreels** [comment]
> Ah this is our enum - I thought it was an official one.
> 
> Frankly, I prefer to re-introduce None and use that as a default @stijnmoreels? It's more explicit when reading the code imo.

I agree! Let's do that.

**Comment by tomkerkhove** [comment]
Let's go for a v1.0.1 version to re-introduce this
