### ISSUE TITLE
Provide Azure Service Bus plugin for interpreting correlation info from messages

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#23]
Provide Azure Service Bus plugin for interpreting correlation info for inbound messages and populate `ICorrelationInfo`, if possible.

This is just an idea and should first be analysed if it's possible and worth the effort.

For an example of what a Service Bus plugin is, see [SeanFeldman/ServiceBus.AttachmentPlugin](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin).

**Comment by stijnmoreels** [comment]
This is done, no? We introduced an extension for this.

**Comment by tomkerkhove** [comment]
Can you link the PR that added it? Looks like it's not linked here and want to verify that everything is there including docs.

**Comment by stijnmoreels** [comment]
> Can you link the PR that added it? Looks like it's not linked here and want to verify that everything is there including docs.

https://github.com/arcus-azure/arcus.messaging/pull/51

**Comment by tomkerkhove** [comment]
We are missing docs on this, can you provide them please?
