### ISSUE TITLE
Remove the `Arcus.Messaging.Pumps.ServiceBus.KeyRotation` project

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.messaging#234]
**Is your feature request related to a problem? Please describe.**
The auto-restart functionality upon rotated credentials is moved towards the Arcus background jobs repository, making the `Arcus.Messaging.Pumps.ServiceBus.KeyRotation` project obsolete.

**Describe the solution you'd like**
Remove the `Arcus.Messaging.Pumps.ServiceBus.KeyRotation` project.

**Comment by fgheysels** [comment]
It is not a project, but merely a type inside Arcus.Messaging

**Comment by stijnmoreels** [comment]
Ah yes, probably about this type: https://github.com/arcus-azure/arcus.messaging/blob/main/src/Arcus.Messaging.Pumps.ServiceBus/KeyRotation/AzureServiceBusKeyRotation.cs
