### ISSUE TITLE
Remove the `CanProcessMessage` method from the `MessageHandler` module 

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.messaging#237]
**Is your feature request related to a problem? Please describe.**
When processing messages, received from message pumps or other systems, we use a `MessageHandler` module (static class) to make sure that we can extract open interfaces from the `IServceProvider`. One of these module functions is called `CanProcessMessage` which validates if a `IMessageHandler` can process based on a messaging context. We have renamed this method to `CanProcessMessageBasedOnContext` because there were also other criteria to filter upon, making the method obsolete.

**Describe the solution you'd like**
Remove the `CanProcessMessage` method from the `MessageHandler` module.

**Comment by pcarmo** [comment]
Not clear how this is different from #297 as there's no other `CanProcessMessage` method.
