### ISSUE TITLE
When calling AddServiceBusQueueMessagePump multiple times only the first registered pump works

### ISSUE THREAD

**Issue by JCunhaCodit** [arcus-azure/arcus.messaging#254]
**Describe the bug**
I have the need to set up two queue message pumps pointing at a different service bus and queue. When I register the two pumps only the first registered works.

**To Reproduce**
In the service configuration set up the pumps: 
```services.AddServiceBusQueueMessagePump(string queueA, 
secretProvider => secretProvider.GetRawSecretAsync(SecretNames.CONNECTIONTOSB1), 
messagePumpOptions =>
                   {
                       messagePumpOptions.Correlation.TransactionIdPropertyName = MessageHeaders.TransactionId;
                       messagePumpOptions.Deserialization.AdditionalMembers = AdditionalMemberHandling.Ignore;
                   })
                   .WithServiceBusMessageHandler<MessageHandlerX, MessageTypeX>();

services.AddServiceBusQueueMessagePump(string queueB, 
secretProvider => secretProvider.GetRawSecretAsync(SecretNames.CONNECTIONTOSB2), 
messagePumpOptions =>
                   {
                       messagePumpOptions.Correlation.TransactionIdPropertyName = MessageHeaders.TransactionId;
                       messagePumpOptions.Deserialization.AdditionalMembers = AdditionalMemberHandling.Ignore;
                   })
                   .WithServiceBusMessageHandler<MessageHandlerY, MessageTypeY>();
```

**Expected behavior**
The messages arriving in queueA ServiceBus1 are processed by message handler X
The messages arriving in queueB ServiceBus2 are processed by message handler Y

**Additional context**
 - Version 1.1.0

**Comment by stijnmoreels** [comment]
Hi @JCunhaCodit , thx for your issue. Can you be more elaborate on the problem, here? This may be caused not by a message pump that isn't registered, but by a too-general message handler implementation. In the code sample you shown, you use `AdditionalMemberHandling.Ignore` which means that any additional JSON properties will be ignored. This means that almost all incoming types are safely parsed. If you combine that with multiple message handlers, you can get problems as the message deserialization works for the wrong kind of message type.

Can you be more strict about this? Can you try that?
Also, could you give us some logging so we can maybe pinpoint the root problem? Thx again.

**Comment by JCunhaCodit** [comment]
Thank you @stijnmoreels,
This is a shortened version of the code but you pinned pointed the problem. I needed the ```AdditionalMemberHandling.Ignore``` but I had too many handlers matching for the same message! 
Now after using the context and an extension method to filter on a message property it works
```
.WithServiceBusMessageHandler<MessageHandlerX, MessageTypeX>();
```
now looks like:
```
 .WithServiceBusMessageHandler<MessageHandlerX, MessageTypeX>( 
 messageContext => messageContext.HasMessageType(ThisIsMessageTypeOnTheHeader));
```

If you agree this can be closed

**Comment by stijnmoreels** [comment]
Ah, that is great news, @JCunhaCodit ! Glad we could help. Your issue here raises a question whether we should maybe be more clear on the documentation of this. I'll follow-up in another issue.

Helping the message routing with a message context filter is indeed a very good solution to handle this problem. Super that you found that. I'll close indeed this issue but feel free to open another issue/discussion if you have something else that you ran into. Always happy to help.
