### ISSUE TITLE
Provide capability to support multiple message handlers based on message body

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#27]
Provide capability to support multiple message handlers based on message body

This is similar to #26, but purely on the message body stream without any deserialization.

**Comment by stijnmoreels** [comment]
So, like adding `.WithMessageHandler`, we should have something that has a predicate with the body stream?
So, the message stream should be resetted after the message handler predicate?

And,  do we allow both message handler registrations with deserialization and without deserialization together, but that it first looks for registrations without deserialization?

**Comment by tomkerkhove** [comment]
> So, like adding `.WithMessageHandler`, we should have something that has a predicate with the body stream?
> So, the message stream should be resetted after the message handler predicate?

That's right!

> And, do we allow both message handler registrations with deserialization and without deserialization together, but that it first looks for registrations without deserialization?

Can you elaborate on this please? You mean provide overloads for both a raw stream and one for deserialized object or?

**Comment by stijnmoreels** [comment]
> > And, do we allow both message handler registrations with deserialization and without deserialization together, but that it first looks for registrations without deserialization?
> 
> Can you elaborate on this please? You mean provide overloads for both a raw stream and one for deserialized object or?

Yes, that's what I mean. That we allow both and that we first look at the handlers that takes the stream directly and then at the handlers with the deserialized object.
Seems logic for me that we take the handlers first that takes in the stream, no?

**Comment by tomkerkhove** [comment]
It should not have priority over the other ones; I think those handlers should provide 2 responses:
1. Bool noting if it's a match
2. Deserialized object that is being passed to the handler to process.

That way folks can mix & match the handlers easily.

I think this might be good to have as a new interface so that this doesn't have to be inlined in the wiring of the handlers maybe?
