### ISSUE TITLE
Improve Messaging documentation

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.messaging#289]
When you go to the documentation page of Arcus Messaging, this is what you see:

![image](https://user-images.githubusercontent.com/3605786/171422140-da1bcc27-6928-4047-b1e1-b0ae9d7a6ae1.png)

We're talking about how to install it, and what the features are, but I'm missing a global 'What is this / Why should i use this' section.   I'd like to have a short introduction section which describes what this project is for, and why you could use it, and that section should be the very first section (before 'Installation').

It could have content like this:

> # Introduction

> Arcus.Messaging provides functionality to easily create message based solutions.   Arcus.Messaging allows you to focus on writing the business logic that is required to handle received messages, while Arcus takes care of all the infrastructural plumbinb code.

Actually, I don't know if I would put the 'Features' and 'Guides' section on the home page as well, since we have this already in the menu on the left side.

Also, I think it would be good to re-order the Message-pums features section:

![image](https://user-images.githubusercontent.com/3605786/171423630-a050a312-602c-4b81-bdd9-23778f32a923.png)

I would put them in this order:

- Azure Service Bus Message pump
- Azure Service Bus Messag pump for Azure Functions
- Customize message pumps

**Comment by stijnmoreels** [comment]
Before we refactor this, please look at the PR that already does focus on the message handling #268 , this isn't shown yet bc it's in preview. The focus is now on message handling instead of on pumps. Please check the merged PR before this.

The introduction page, sure, that can be improved. 👍

**Comment by stijnmoreels** [comment]
Aha, we already added an introduction in #280.
