### ISSUE TITLE
ServiceBusMessageBuilder is in wrong namespace

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.messaging#291]
The `ServiceBusMessageBuilder` type in `Arcus.Messaging.ServiceBus.Core` is defined in the namespace `Microsoft.Azure.ServiceBus`.
This namespace is a relic from the now deprecated Microsoft.Azure.Servicebus package.   
I believe the `ServiceBusMessageBuilder` was put in this namespace, because it formerly created instances of type `Message` which was in the `Microsoft.Azure.ServiceBus` namespace.

The `Microsoft.Azure.ServiceBus` package is replaced by the `Azure.Messaging.ServiceBus` package and the `Message` type is replaced by the `ServiceBusMessage` type.
The `ServiceBusMessageBuilder` namespace should be put in:
a) the `Azure.Messaging.ServiceBus` namespace
or
b) the `Arcus.Messaging.ServiceBus` namespace.

I see why we would put it in the `Azure.Messaging.ServiceBus` namespace though.  It will be much easier discoverable, and it creates types that are in that namespace as well.

**Comment by stijnmoreels** [comment]
Ah, yes, that should be moved indeed.
Let's use `Azure.Messaging.ServiceBus` instead, then. 👍 

Good thing we didn't released this yet 😉 .
