### ISSUE TITLE
ObjectExtensions.AsServiceBusMessage should be removed from Arcus.Messaging.ServiceBus.Core

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.messaging#292]
The `AsServiceBusMessage` extension method is an extension method on `object` which is imho not a good idea.
Next to that, as far as I can see, this extension method has been replaced by the `ServiceBusMessageBuilder` builder-type which is in my humble opinion a far better approach to construct `ServiceBusMessage` instances.

This extension method should therefore be deleted, but maybe we should first declare it as obsolete.

**Comment by stijnmoreels** [comment]
Yes, that's also the reason why we introduced the builder. (Thought that we already made the extension obsolete, though 😄 ) Thx for mentioning!
