### ISSUE TITLE
Provide support for running multiple pumps in same app

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#33]
Provide support for running multiple pumps in same app to allow resource consolidation

**Comment by tomkerkhove** [comment]
This is already the case, right @stijnmoreels ? Or is it not due to DI voodoo for configuration?

**Comment by stijnmoreels** [comment]
Yes, is already the case I think. The pump is registered as a `IHostedService` so multiple registrations are just collected under that type.

**Comment by tomkerkhove** [comment]
That's correct, but don't we register the configuration in the DI as well?

**Comment by stijnmoreels** [comment]
> That's correct, but don't we register the configuration in the DI as well?

Ah, yes, we'll have to maybe change this so allow multiple configurations in the DI for each message pump. Or pass it along the ctor of the pump?

**Comment by tomkerkhove** [comment]
If we can use the ctor that's ok for me, otherwise your alternative is ok

**Comment by stijnmoreels** [comment]
By using 
```csharp
services.AddHostedService(serviceProvider => 
{
    return new AzureServiceBusMessagePump(...))
})
```

We can send the settings directly to the hosted service instead of registering them as a singleton.

**Comment by tomkerkhove** [comment]
All is fine, as long as it's done by using user-friendly extensions like we have today.
