### ISSUE TITLE
Introduce W3C correlation tracking with automatic dependency tracking

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.messaging#342]
**Is your feature request related to a problem? Please describe.**
Currently, any built-in Microsoft dependencies in the message handlers implementations are not automatically tracked without Arcus extensions.

**Describe the solution you'd like**
Make use of the `Diagnostic-Id` application property which is the `traceparent` of the W3C correlation relationship instead of custom application properties. That way, both Arcus and built-in Microsoft dependencies are tracked with the same parent.

**Comment by fgheysels** [comment]
Just as with what we have in webapi, this will be a huge improvement :)
