### ISSUE TITLE
Provide support for key rolling for Service Bus

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#37]
Provide support for key rolling for Service Bus so that the pump restarts when access is revoked.

**Comment by stijnmoreels** [comment]
Hmm, where exactly was it again that the `ISecretProvider` is called? I _guess_ that I should update the `AzureServiceBusMessagePump` to include this functionality; but not sure where the `ISecretProvider` comes into play.

**Comment by tomkerkhove** [comment]
It's used to determine the connection string but the impact would be that the host would need to stop and restart itself to reset the pump itself.

**Comment by stijnmoreels** [comment]
> It's used to determine the connection string but the impact would be that the host would need to stop and restart itself to reset the pump itself.

Yes, but isn't the connection string retrieved at post-startup/pre-execution and only once? So, how would that help? I mean, the restarting.

**Comment by tomkerkhove** [comment]
The thing we are trying to tackle here is when a user/process decides to regenerate the authentication keys (aka key rolling) for Service bus, the message pump will start failing.

We should provide a way where the message pump detects authentication issues and stops the host. After that it refetches the connection string and starts back up again.

**Comment by stijnmoreels** [comment]
Aha, that's already somewhat clearer.

**Comment by tomkerkhove** [comment]
Sorry for the bad info before that, it's hard to translate what's in my head into text 😅

**Comment by stijnmoreels** [comment]
😆 np, that's why I asked to be sure.

**Comment by stijnmoreels** [comment]
1. I'm gonna provide a test infrastructure in the messaging repo to test in an easy manner different message pump configurations (without Docker, but self-containing).
2. The EventGrid issue about the current parsing functionality should be fixed since I still get issues on that: [arcus.eventgrid/106](https://github.com/arcus-azure/arcus.eventgrid/issues/106)
3. I've to find some kind of exception that the message receiver in the message pump throws during execution so we can spot the authentication failure.

**Comment by tomkerkhove** [comment]
> 2\. The EventGrid issue about the current parsing functionality should be fixed since I still get issues on that: [arcus.eventgrid/106](https://github.com/arcus-azure/arcus.eventgrid/issues/106)

Not sure how this relates here, can you elaborate please?



> 3\. I've to find some kind of exception that the message receiver in the message pump throws during execution so we can spot the authentication failure.

You can verify easily test this:
1. Start valid pump
2. Rotate key in Azure portal
3. Et voila

You can find all exceptions here https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions but I'm expecting it to be `UnauthorizedAccessException`

**Comment by stijnmoreels** [comment]
Yes :D was to leave a mental note here that not all building blocks are ready.

**Comment by stijnmoreels** [comment]
> > 2. The EventGrid issue about the current parsing functionality should be fixed since I still get issues on that: arcus.eventgrid/106
> 
> Not sure how this relates here, can you elaborate please?

The issue remains that Service Bus messages can have Jason bodies that contains either a single or multiple events. Our eventgrid parsing is not (yet) updated to handle this, as well as the JSON parsing in the message pump.
It's true, maybe we could work around the issue and just focus on the authorization.

**Comment by stijnmoreels** [comment]
In terms of testing the authorization failure. Is their a way to regenerate a Service Bus queue/topic connection string for this?

It's not really about Key Vault, if I'm correct, just the authorization of the message receiver with the connection string to the Service Bus entity from Key Vault. Right?

**Comment by tomkerkhove** [comment]
You can rotate them in the Azure portal to test this.

It's indeed mainly to handle the unauthorized scenario, but once it is detected we should refetch the connection string and try again.

Does that clarify what we want to achieve here?

**Comment by stijnmoreels** [comment]
Yes, I think it does. I'll work on that.

**Comment by stijnmoreels** [comment]
This was by the way the issue of JSON parsing I was refering to:
![image](https://user-images.githubusercontent.com/9039753/74419098-b1282a00-4e49-11ea-9c29-8e5c551d88cb.png)

**Comment by stijnmoreels** [comment]
I think I need some more guidance on what we want to add/test. Can you for example show me how to rotate the connection of a Service Bus connection?

**Comment by tomkerkhove** [comment]
With rotation of a key I'm referring to regenerating the Service Bus authentication key.

You can do this in the Azure portal for example:
![image](https://user-images.githubusercontent.com/4345663/80100672-93c1bb80-8570-11ea-97f4-7727295ebaf6.png)

The impact on us would be that the message pump will stop working and/or throw authentication exceptions so we should work around that and automatically re-fetch the connection string and restart the pump.

Reason is that for security reasons there can be automated processes that rotate the key every x hours/days/weeks to reduce exposure of leaked secrets.

Makes more sense?
