### ISSUE TITLE
Rename `Pause` to `Start` in `IMessagePumpLifetime`

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.messaging#387]
**Describe the bug**
We have mistaken the `IMessagePumpLifetime` interface as we have named a method `Pause` while it is actually `Start`ing the message pump.

**To Reproduce**
Look for the `IMessagePumpLifetime` interface.

**Expected behavior**
Rename the interface correctly.

**Additional context**
 - v1.4

**Comment by fgheysels** [comment]
Do we need to go through this, since we've deprecated this interface ?

**Comment by stijnmoreels** [comment]
Think the interface itself is not deprecated?
https://github.com/arcus-azure/arcus.messaging/blob/main/src/Arcus.Messaging.Pumps.Abstractions/IMessagePumpLifetime.cs
