### ISSUE TITLE
EventHubsMessageRouting (?) in Azure Functions logs all invocations with operationname 'Process' 

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.messaging#404]
When using Arcus.Messaging to process messages coming from eventhub in an Azure Function, the Function invocations in Application Insights are logged with an operation-name 'Process'.

Is it possible to modify / specify the operation-name that must be used ?

**Comment by stijnmoreels** [comment]
No, not right now. We pas in `operationName: null` for the router, so it gets assigned `Process` automatically. We could extend the router options with the possibility to assign an operation name, though.

**Comment by fgheysels** [comment]
That would be great!
