### ISSUE TITLE
Add Azure Service Bus entity type to request tracking

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.messaging#413]
**Is your feature request related to a problem? Please describe.**
Currently, we do not have the entity type of the Azure Service Bus entity in the request tracking because it is not available in the message context.

**Describe the solution you'd like**
Add the Azure Service Bus entity type to the message context so we can use it when tracking the request telemetry.

**Describe alternatives you've considered**
None.

**Comment by fgheysels** [comment]
What exactly do you mean with the entity type ?  Do you mean the fact whether you're reading from a queue or topic ?

**Comment by stijnmoreels** [comment]
> What exactly do you mean with the entity type ? Do you mean the fact whether you're reading from a queue or topic ?

Yes, that is correct. 👍
