### ISSUE TITLE
Provide more thorough integration scenarios for message pump

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#44]
Provide more thorough integration scenarios for message pump which interacts more with the messages such as abandon, complete, et al.

**Comment by stijnmoreels** [comment]
After consideration, not sure if we can test this proparly with the Service Bus relationship. The message pump handles a lot for us, but makes testing low-level stuff a lot harder too.

**Comment by tomkerkhove** [comment]
Agreed!
