### ISSUE TITLE
Unable to invoke the MessagePump Circuitbreaker

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.messaging#443]
I have a project where I use Arcus.Messaging and where I make use of the new Circuitbreaker functionality.

During testing, I've noticed that the Circuitbreaker functionality doesn't kick in when requested.  Logs of my application show this exception:

> System.InvalidOperationException: The message processor is already running and needs to be stopped in order to perform this operation

This can be traced back to the `StopProcessingMessagesAsync` method of the `AzureServiceBusMessagePump` class.  Apparently this exception is thrown in that try-block.

Further investigation showed that the stacktrace contains a reference to a method `EnsureNotRunningAndInvoke` which is a member method of `ServiceBusProcessor` class.

Looking at that code shows that the logic for removing an eventhandler on the `ProcessMessageAsync`  and `ProcessErrorAsync` methods are calling this method.   [click](https://github.com/Azure/azure-sdk-for-net/blob/330cb2492a10245a0b43e133cfd19685476f11d8/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs#L372)

This means that the `StopProcessingMessagesAsync` method must first call the `StopProcessingAsync` method on the `ServiceBusProcessor` before removing the eventhandlers.

![image](https://github.com/arcus-azure/arcus.messaging/assets/3605786/151fabeb-437b-4b1c-a75c-ee5a00b6fb9f)

**Comment by stijnmoreels** [comment]
Think this will be resolved with #442

**Comment by fgheysels** [comment]
This remark on the `ProcessMessageAsync` event is actually a bit worrying

>  /// <remarks>
        /// It is not recommended that the state of the processor be managed directly from within this handler; requesting to start or stop the processor may result in
        /// a deadlock scenario.
        /// </remarks>

Because, that's what we're actually doing...  When we call the circuitbreaker from within the ProcessMessageAsync eventhandler, we're actually stopping the processor.

**Comment by stijnmoreels** [comment]
Yes, saw that too - am working on your branch to fully use the message receiver instead.

**Comment by stijnmoreels** [comment]
This is now being handled, right?

**Comment by fgheysels** [comment]
Yes, this was handled in https://github.com/arcus-azure/arcus.messaging/pull/444
