### ISSUE TITLE
Provide simplified approach to wire up the Service Bus pump

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#48]
Provide simplified version to use Service Bus pump which does not require you to use a func to get the connection string, but a secret key name instead:
```csharp
services.AddServiceBusTopicMessagePump<EmptyMessagePump>("Receive-All", "My-Secret-Name");
```

The documentation should clearly state that it will look it up by using `ISecretProvider` and not `IConfigurationProvider`.

**Comment by tomkerkhove** [comment]
Now another approach would be that we:
1. Query ISecretProvider
2. Query IConfiguration

And determine it based on that, would this make it more user-friendly?

/cc @stijnmoreels @gverstraete @wseye

**Comment by gverstraete** [comment]
And what would you do when you find it in both? - I would rather go for the first approach

**Comment by tomkerkhove** [comment]
> And what would you do when you find it in both?

First one wins, in this case ISecretProvider

**Comment by gverstraete** [comment]
> > And what would you do when you find it in both?
> 
> First one wins, in this case ISecretProvider

Ok!
I think the question you need to ask is, are we going to use this only with KV Arcus integration? - And I'm not sure what my answer on that one should be :)

**Comment by tomkerkhove** [comment]
We already have overloads where you can specify how to look it up via `ISecretProvider` (https://github.com/arcus-azure/arcus.messaging/blob/master/src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs#L23) or via IConfiguration (https://github.com/arcus-azure/arcus.messaging/blob/master/src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs#L41) so you can use it without Arcus Security.

What we want to achieve here is simplify it and do all of that under the covers.

Anyhow, let's go with `ISecretProvider` for this @stijnmoreels:
```csharp
services.AddServiceBusTopicMessagePump<EmptyMessagePump>("Receive-All", "My-Secret-Name");
```

If people don't like it they can still specifiy it themselves.
