### ISSUE TITLE
Write introduction blog post for messaging

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#67]
Write introduction blog post for messaging which discusses the focus of the project and what it brings to the table

**Comment by tomkerkhove** [comment]
Will you add it to our Codit blog @stijnmoreels?

**Comment by stijnmoreels** [comment]
> Will you add it to our Codit blog @stijnmoreels?

Was there not a picture I had to add?

**Comment by tomkerkhove** [comment]
Everything was resolved so figured it was good to go; you can still add it in the blog post if it's missing out or what are you saying here?

**Comment by stijnmoreels** [comment]
> Everything was resolved so figured it was good to go; you can still add it in the blog post if it's missing out or what are you saying here?

Added the picture and added a blog draf with the contents of the markdown file.
What are the next steps?

Ps.: for the summary, I extracted two sentences in the intro. Not sure if this is correct.

**Comment by tomkerkhove** [comment]
I've moved the image and removed myself as author since you did everything but for the rest it looks ok.

One thing I'm missing, and forgot to mention this in the PR, is a small outro with:
- Pointer to websites as summary
- Small elaboration on what is next

Feel free to add this or I can pick this up as well.

**Comment by stijnmoreels** [comment]
The elaboration on what's next is a bit difficult for me 😞 .

**Comment by tomkerkhove** [comment]
No worries, will send a proposal!

**Comment by stijnmoreels** [comment]
I guess it's out of our hands now so we can close this?

**Comment by tomkerkhove** [comment]
Let's wait until it's published.
