### ISSUE TITLE
Securing TCP health check

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.messaging#86]
**Is your feature request related to a problem? Please describe.**
Right now, our TCP health endpoint allows any client, any number of clients, and non-ssl connections.

**Describe the solution you'd like**
By expending the configurable options in the container, we can provide these kind of extra security options for consumers.

**Describe alternatives you've considered**
Using the [WatsonTcp](https://github.com/jchristn/WatsonTcp) could also be an option.

**Comment by tomkerkhove** [comment]
Well it's up to the orchestrator to reduce the access for now.

However, it can be valuable but I'm not sure we should add it already until we have customer demand? Unless it's pretty slick but always try to wait until we have customer demand.

**Comment by stijnmoreels** [comment]
Ok, is fine by me. Just, with security, I tend to have these things already there. I'ts not a "feature" in that sense for me.

**Comment by tomkerkhove** [comment]
Let's wire up a PR and see what it looks like/takes to enable it

**Comment by tomkerkhove** [comment]
FWIW - Mostly there's no security on these kind of health probes and handled on different layer.

See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-tcp-liveness-probe

**Comment by stijnmoreels** [comment]
I'll close this until we have consumer demand for this.
